image: python:3.5
pipelines:
  default:
    - step:
        name: Build and test
        script:
          - export PyFLOTRAN_DIR=`pwd`
          - export PFLOTRAN_DIR='nil'
          - python setup.py install
          - python regression.py -v
